CREATE TABLE IF NOT EXISTS jira_issue (
    issue_key VARCHAR(255) PRIMARY KEY,
    jira_id VARCHAR(255),
    project_key VARCHAR(255),
    self_url VARCHAR(500),
    summary TEXT,
    issue_type VARCHAR(255),
    status VARCHAR(255),
    priority VARCHAR(255),
    resolution VARCHAR(255),
    assignee VARCHAR(255),
    assignee_email VARCHAR(255),
    reporter VARCHAR(255),
    reporter_email VARCHAR(255),
    created TIMESTAMP,
    updated TIMESTAMP,
    resolved TIMESTAMP,
    time_spent_seconds BIGINT,
    original_estimate_seconds BIGINT,
    remaining_estimate_seconds BIGINT,
    story_points DECIMAL(10,1)
);