version: "3.9"

services:
  jira-fetch-service:
    image: ghcr.io/${IMAGE_NAMESPACE}/jira-fetch-service:latest
    env_file: .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "${JIRA_FETCH_SERVICE_PORT}:8081"
    depends_on:
      - postgres
      - kafka

  reporting-service:
    image: ghcr.io/${IMAGE_NAMESPACE}/reporting-service:latest
    env_file: .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_SQL_INIT_MODE=never
    ports:
      - "${REPORTING_SERVICE_PORT}:8082"
    depends_on:
      - jira-fetch-service
      - postgres
      - kafka

  chart-service:
    image: ghcr.io/${IMAGE_NAMESPACE}/chart-service:latest
    env_file: .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "${CHART_SERVICE_PORT}:8083"
    depends_on:
      - reporting-service

  email-service:
    image: ghcr.io/${IMAGE_NAMESPACE}/email-service:latest
    env_file: .env
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "${EMAIL_SERVICE_PORT}:8084"
    depends_on:
      - redis
      - rabbitmq

  excel-service:
    image: ghcr.io/${IMAGE_NAMESPACE}/excel-service:latest
    env_file: .env
    environment:
      - EXCEL_REPORTS_DIR=/data
      - EXCEL_CHECKPOINT_DIR=/data
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "${EXCEL_SERVICE_PORT}:8085"
    volumes:
      - excel_data:/data
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "${KAFKA_PORT}:9092"
    depends_on:
      - zookeeper

volumes:
  postgres_data:
  excel_data:
