# Use Eclipse Temurin JRE 21 as the base image
FROM eclipse-temurin:21-jre

# Set the working directory
WORKDIR /app


COPY target/jira-fetch-service-0.0.1-SNAPSHOT.jar app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
